### ISSUE TITLE
cloudmesh installer test fails

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-installer#9]
_________________________ Test_installer.test_cms_info _________________________

self = <test_installer.Test_installer object at 0x7f5e569e8a50>

def test_cms_info(self):
    banner("test_cms_info")
    print("PWD:", os.getcwd())

    cmd = "cms info"
    result = Shell.run(cmd)
    print(result)
  assert "cloudmesh.common" in result
E AssertionError: assert 'cloudmesh.common' in '* cloudmesh.test\n* cloudmesh.test.CloudmeshTest\n* cloudmesh.test.version\n* cloudmesh.test.command\n* cloudmesh.test.command.test\n'

looks like somehow the info command in cmd5 does not return cloudmesh.common
Maybe we need to run make readme in installer and test for something in the manual page.
however info would be good to figure out why its not working.

maybe we just need a new function that lists all packages in a namespace such as cloudmesh

**Comment by jpfleischer** [comment]
it wasnt working because it was doing `pip install -e .` instead of `make pip`
https://github.com/cloudmesh/cloudmesh-installer/actions/runs/7521440079/job/20472283899#step:8:51
working now
